/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.wocken.wedding

import com.wocken.wedding.guest.GuestHandler
import com.wocken.wedding.guest.GuestModule
import com.wocken.wedding.invitation.InvitationHandler
import com.wocken.wedding.invitation.InvitationModule
import com.wocken.wedding.invitationsearch.GuestInvitationSearchHandler
import com.wocken.wedding.invitationsearch.GuestInvitationSearchModule
import ratpack.guice.BindingsSpec
import ratpack.guice.Guice
import ratpack.handling.Chain
import ratpack.server.RatpackServer
import ratpack.server.RatpackServerSpec
import ratpack.server.ServerConfig

class App {
    static void main(String... args) throws Exception {
        RatpackServer.start({ RatpackServerSpec server ->
            server
                .registry(Guice.registry({ BindingsSpec bindingsSpec ->
                    bindingsSpec.module(GuestModule)
                    bindingsSpec.module(InvitationModule)
                    bindingsSpec.module(ResponseHeaderModule)
                    bindingsSpec.module(GuestInvitationSearchModule)
                }))
                .serverConfig(
                    ServerConfig.embedded()
//                        .publicAddress(new URI("http://company.org"))
                        .port(8080)
                )
                .handlers({ Chain chain ->
                    chain
                        .all(ResponseHeaderHandler)
                        .path("guests", GuestHandler)
                        .path("guests/:id", GuestHandler)
                        .path("invitations", InvitationHandler)
                        .path("invitations/:id", InvitationHandler)
                        .path("guest_invitations/search", GuestInvitationSearchHandler)
                })
        })
    }
}